<?php
$value = array (
  'wwwprefix' => 'http://localhost:8888/zuituware',
  'imgprefix' => 'http://localhost:8888/zuituware',
  'cssprefix' => 'http://localhost:8888/zuituware',
  'sitename' => '最土网',
  'sitetitle' => '精品团购每一天',
  'abbreviation' => '最土',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-9',
  'editor' => 'kind',
  'indexteam' => '10',
  'sideteam' => '5',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
);
?>